"""Additive expansion seed: insert 218 researched interview questions into the questions table.

Question data is inlined (self-contained, no runtime vault dependency).

Fields map to the questions table schema:
  questions(id, company, role, topic, difficulty, question, source)
  topic  = the JSON "topic" field (e.g. "MCP internals", "mechanistic-interpretability-superposition")
  role   = the JSON "role" field (ai-eng | ml | ds | fde | research | quant)
  pillar is embedded by tagging topic as "<original-topic> | pillar:<PillarName>" so that
         get_questions(topic="CS Fundamentals") or get_questions(topic="Research & Frontier")
         will match these rows via the LIKE %...% filter.

DEDUP: INSERT OR IGNORE on the unique question text — re-runs are completely safe.
ADDITIVE: no updates, no deletes.

Run:
  uv run python scripts/seed_questions_expansion.py           (dry run — counts only)
  uv run python scripts/seed_questions_expansion.py --apply   (writes to live DB)
"""

from __future__ import annotations

import sys

from eklavya.db import connect, init_db

# Each tuple: (question, topic, difficulty, role, company, source)
# topic = "<original JSON topic> | pillar:<pillar name>" so LIKE-based filtering on both works.
QUESTIONS: list[tuple[str, str, str, str, str, str]] = [
    ('Explain the Model Context Protocol (MCP) architecture: what are the roles of host, client, and server, and how does JSON-RPC fit in? Why does MCP solve the N×M integration problem?', 'MCP internals | pillar:AI Agents & Orchestration', 'medium', 'ai-eng', 'Anthropic', 'https://www.datacamp.com/blog/mcp-interview-questions'),
    ("You are scaling an MCP server horizontally behind a load balancer. A user's second request lands on a different server instance and the agent loses session context. What are the three architectural options to handle this, and what are the tradeoffs?", 'MCP internals | pillar:AI Agents & Orchestration', 'hard', 'ai-eng', '', 'https://www.youtube.com/watch?v=ARn1dzfUuyU'),
    ('How do you safely expose a production PostgreSQL database to an AI agent via MCP? Walk through the security layers you would add.', 'MCP internals | pillar:AI Agents & Orchestration', 'hard', 'ai-eng', '', 'https://www.hirist.tech/blog/top-mcp-interview-questions-answers-ai-agents-tool-calling'),
    ("What is DSPy's core abstraction — Signature + Module — and how does it differ from writing a LangChain prompt template by hand? What problem does automated prompt optimisation solve that manual prompting cannot?", 'DSPy | pillar:AI Agents & Orchestration', 'medium', 'ai-eng', '', 'https://www.dbreunig.com/2025/06/10/let-the-model-write-the-prompt.html'),
    ("When would you choose DSPy's BootstrapFewShot over MIPROv2 as the optimizer? What does each actually search over?", 'DSPy | pillar:AI Agents & Orchestration', 'hard', 'ai-eng', '', 'https://towardsdatascience.com/systematic-llm-prompt-engineering-using-dspy-optimization'),
    ('What is the difference between a LangGraph Checkpointer and a LangGraph Store (cross-thread memory)? Give a concrete use case for each.', 'LangGraph patterns | pillar:AI Agents & Orchestration', 'medium', 'ai-eng', '', 'https://www.interviewcoder.co/blog/langgraph-interview-questions'),
    ('Compare the Supervisor pattern and the Swarm (peer handoff) pattern in LangGraph multi-agent systems. When does each break down?', 'LangGraph patterns | pillar:AI Agents & Orchestration', 'hard', 'ai-eng', '', 'https://cloudsoftsol.com/interview-questions/langgraph-interview-questions-answers'),
    ('Two parallel LangGraph branches both write to the same TypedDict state field that has no reducer defined. What happens, and how do you fix it?', 'LangGraph patterns | pillar:AI Agents & Orchestration', 'medium', 'ai-eng', '', 'https://www.udemy.com/course/langgraph-ai-agent-interview-questions'),
    ("An agent needs to remember: (a) today's conversation, (b) a user's standing preferences set last month, (c) the steps of the current multi-step task, and (d) how to call a particular API. Map each to the correct memory type and a concrete storage mechanism.", 'agent memory and planning | pillar:AI Agents & Orchestration', 'medium', 'ai-eng', '', 'https://www.aemonline.net/blog/25-advanced-agentic-ai-interview-questions-for-2026-with-answer-updated-february-2026'),
    ('A senior engineer says your agentic eval framework is incomplete because you only measure final answer quality with RAGAS. What are the additional axes a production agentic eval must cover, and why does each matter?', 'evals engineering — agentic evals | pillar:AI Agents & Orchestration', 'hard', 'ai-eng', 'Anthropic', 'https://prachub.com/resources/ai-engineer-interview-questions-2026-rag-agents-evals-and-production-systems'),
    ('What are the known failure modes of using an LLM as a judge, and what practical mitigations do you put in place before trusting its scores in a CI pipeline?', 'evals engineering — LLM-as-judge | pillar:AI Agents & Orchestration', 'hard', 'ai-eng', '', 'https://gitgood.dev/blog/complete-guide-rag-interview-questions-2026'),
    ('Explain reciprocal rank fusion (RRF). Why is it preferred over score-based fusion when combining BM25 and dense retrieval results?', 'advanced RAG — hybrid and rerank | pillar:RAG & Vector Retrieval', 'medium', 'ai-eng', '', 'https://gitgood.dev/blog/complete-guide-rag-interview-questions-2026'),
    ('When does Graph RAG beat vanilla vector RAG, and when does it not? Give a concrete decision framework.', 'advanced RAG — Graph RAG | pillar:RAG & Vector Retrieval', 'hard', 'ai-eng', '', 'https://gitgood.dev/blog/complete-guide-rag-interview-questions-2026'),
    ('Explain the HNSW algorithm: how is the multi-layer graph built, and how does search proceed? What do the parameters M and efSearch control, and what is the recall-latency tradeoff?', 'vector DB internals — HNSW | pillar:RAG & Vector Retrieval', 'hard', 'ai-eng', '', 'https://www.kunwar.page/chapter/059-vector-index-internals-hnsw-ivf-scann-faiss'),
    ('Compare IVF-PQ (Inverted File Index with Product Quantization) and HNSW on memory footprint, query latency, recall, and update cost. For a 500M-vector corpus where memory is constrained, which do you pick and why?', 'vector DB internals — IVF | pillar:RAG & Vector Retrieval', 'hard', 'ai-eng', '', 'https://medium.com/@darshantank_55417/how-does-avectordb-handle-million-scale-vector-search-in-milliseconds-with-hnsw-d9fdeee1d098'),
    ('A RAG system scores 0.85 on RAGAS faithfulness but users complain the answers are unhelpful. What is likely going wrong and how do you diagnose it?', 'advanced RAG — evals | pillar:RAG & Vector Retrieval', 'medium', 'ai-eng', '', 'https://myengineeringpath.dev/genai-engineer/evaluation'),
    ('Prove that minimising cross-entropy loss H(p, q) over a model q is equivalent to minimising KL divergence D_KL(p || q). What does this mean for maximum likelihood estimation?', 'information theory | pillar:ML Theory & Math Foundations', 'hard', 'research', 'DeepMind', 'https://github.com/mikenguyen13/ai_in_action/blob/main/037-information-theory-kl-divergence-mutual-information.qmd'),
    ('What is mutual information I(X; Y), and why does it use KL divergence rather than, say, Euclidean distance between the joint and product-of-marginals distributions?', 'information theory | pillar:ML Theory & Math Foundations', 'hard', 'research', '', 'https://stats.stackexchange.com/questions/563757/why-does-mutual-information-use-kl-divergence'),
    ("State Itô's Lemma for a 1D diffusion process. Apply it to derive the SDE for Y_t = ln(X_t) when X_t follows geometric Brownian motion dX_t = μX_t dt + σX_t dW_t. Why does the drift of Y_t differ from μ?", 'stochastic calculus | pillar:ML Theory & Math Foundations', 'hard', 'research', 'Jane Street', 'https://www.datainterview.com/blog/stochastic-calculus-interview-questions'),
    ('What is a filtration {F_t} in stochastic calculus, and why is it essential for defining adapted processes and conditional expectations in the context of financial modelling?', 'measure theory | pillar:ML Theory & Math Foundations', 'hard', 'research', 'Two Sigma', 'https://www.linkedin.com/posts/nikita-singh-iitk_top-interview-quant-questions-related-to-activity-7193540920326189057-b2Ww'),
    ("State the KKT conditions for a constrained optimisation problem. For a convex problem, when are the KKT conditions not only necessary but also sufficient? What is Slater's condition?", 'optimization theory | pillar:ML Theory & Math Foundations', 'hard', 'research', 'DeepMind', 'https://climbtheladder.com/convex-optimization-interview-questions'),
    ('Why is L2 regularisation mathematically equivalent to placing a Gaussian prior on model weights in a Bayesian MAP framework? What prior does L1 regularisation correspond to?', 'optimization theory | pillar:ML Theory & Math Foundations', 'medium', 'research', '', 'https://www.sundeepteki.org/advice/the-ultimate-ai-research-scientist-interview-guide-cracking-anthropic-openai-google-deepmind-top-ai-labs-in-2026'),
    ("You want to estimate the causal effect of education on wages using OLS, but suspect 'ability' is an unobserved confounder. Explain why OLS is biased, what an instrumental variable (IV) is, and what two conditions a valid instrument must satisfy.", 'econometrics — instrumental variables | pillar:Econometrics & Statistics', 'medium', 'ds', '', 'https://wol.iza.org/articles/using-instrumental-variables-to-establish-causality/long'),
    ('Explain the difference between MLE and MAP estimation. When does MAP reduce to MLE, and what are conjugate priors? Give an example of a conjugate prior pair.', 'Bayesian methods | pillar:Econometrics & Statistics', 'easy', 'ds', '', 'https://www.datacamp.com/blog/statistics-interview-questions'),
    ('What is Markov Chain Monte Carlo (MCMC), and why is it needed in Bayesian inference? Explain the Metropolis-Hastings acceptance step and why it ensures samples come from the correct posterior.', 'Bayesian methods — MCMC | pillar:Econometrics & Statistics', 'hard', 'research', '', 'https://www.datacamp.com/blog/statistics-interview-questions'),
    ('Explain the key differences between a process and a thread: what do they share, what is private, and why is a thread context switch cheaper than a process context switch?', 'operating-systems-processes-threads | pillar:CS Fundamentals', 'easy', 'fde', '', 'https://www.interviewbit.com/operating-system-interview-questions/'),
    ('Walk through what happens — at every layer of the OS — when a user-space program accesses a virtual address that is not currently in physical RAM (a page fault).', 'operating-systems-virtual-memory | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.interviewbit.com/operating-system-interview-questions/'),
    ('Compare Round Robin, Shortest Job First (SJF), and Completely Fair Scheduler (CFS). What metric does each optimize, and when does each break down?', 'operating-systems-scheduling | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.golinuxcloud.com/operating-system-interview-questions/'),
    ('State the four Coffman conditions for deadlock. For each one, give a concrete example of how to break it in a real system.', 'operating-systems-synchronization | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.wecreateproblems.com/interview-questions/operating-system-interview-questions'),
    ('What is the Translation Lookaside Buffer (TLB), and what are the performance consequences of a TLB shootdown in a multi-core system?', 'operating-systems-virtual-memory | pillar:CS Fundamentals', 'hard', 'fde', 'Google', 'https://www.interviewbit.com/operating-system-interview-questions/'),
    ("Describe TCP's three-way handshake and four-way teardown. Why does the passive closer enter TIME_WAIT, and what problems can a large number of TIME_WAIT sockets cause in a high-throughput service?", 'computer-networks-tcp | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.interviewbit.com/networking-interview-questions/'),
    ('Explain the key differences between HTTP/1.1, HTTP/2, and HTTP/3. How does each version address head-of-line (HOL) blocking?', 'computer-networks-http | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.interviewbit.com/networking-interview-questions/'),
    ('Trace a TLS 1.3 handshake step by step. How does it differ from TLS 1.2, and why does it achieve forward secrecy by default?', 'computer-networks-tls | pillar:CS Fundamentals', 'hard', 'fde', '', 'https://cyberinterviewprep.com/resources/security-engineer-interview-prep-faang'),
    ('How does TCP congestion control work? Explain slow start, congestion avoidance (AIMD), fast retransmit, and fast recovery. What is CUBIC and why does Linux use it?', 'computer-networks-tcp | pillar:CS Fundamentals', 'hard', 'fde', '', 'https://www.interviewbit.com/networking-interview-questions/'),
    ('Compare B+tree and LSM-tree storage engines for a write-heavy workload. When would you choose RocksDB (LSM) over PostgreSQL (B+tree), and what are the downsides?', 'database-internals-indexing | pillar:CS Fundamentals', 'medium', 'ai-eng', 'Meta', 'https://skillsuites.com/storage-engine-internals/'),
    ('Explain how PostgreSQL implements MVCC. How does it avoid read-write conflicts, and what is the role of VACUUM?', 'database-internals-mvcc | pillar:CS Fundamentals', 'hard', 'fde', '', 'https://www.datacamp.com/blog/dbms-interview-questions'),
    ('Explain the four ACID properties. For each, name one concrete failure scenario it protects against, and the mechanism the database uses.', 'database-internals-transactions | pillar:CS Fundamentals', 'easy', 'fde', '', 'https://www.datacamp.com/blog/dbms-interview-questions'),
    ('A slow query does a full table scan on a 100M-row table even though there is an index on the WHERE column. What are five possible reasons the query planner is ignoring the index?', 'database-internals-indexing | pillar:CS Fundamentals', 'hard', 'fde', 'Gartner', 'https://www.golinuxcloud.com/dbms-interview-questions/'),
    ("Explain how Raft achieves consensus. Walk through leader election and log replication, and explain what 'committed' means in Raft.", 'distributed-systems-consensus | pillar:CS Fundamentals', 'hard', 'research', 'Anthropic', 'https://www.algoroq.io/interview-questions/consensus-algorithms/'),
    ('State the CAP theorem precisely, explain why you can only guarantee two of the three properties during a network partition, and give a real system example for each of CP and AP.', 'distributed-systems-cap | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.algoroq.io/interview-questions/cap-theorem/'),
    ('Compare synchronous vs. asynchronous replication. In a primary-replica setup, what guarantees does each provide, and what is the durability vs. latency tradeoff?', 'distributed-systems-replication | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.designgurus.io/system-design-interview/concepts/replication-consistency'),
    ('What is split-brain in a distributed system, and how does Raft prevent it? What happens to availability during a network partition in a Raft cluster of 5 nodes?', 'distributed-systems-consensus | pillar:CS Fundamentals', 'hard', 'research', 'DeepMind', 'https://www.algoroq.io/interview-questions/consensus-algorithms/'),
    ('What is the Chomsky hierarchy? Describe each level with its corresponding automaton and an example language at each level.', 'theory-of-computation-automata | pillar:CS Fundamentals', 'medium', 'research', '', 'https://www.geeksforgeeks.org/theory-of-computation/theory-of-computation-automata-tutorials/'),
    ('Define the complexity classes P, NP, NP-hard, and NP-complete. Give a concrete example problem in each, and explain why most researchers believe P ≠ NP but cannot prove it.', 'theory-of-computation-pnp | pillar:CS Fundamentals', 'medium', 'research', 'Anthropic', 'https://climbtheladder.com/theory-of-computation-interview-questions/'),
    ('What is the Halting Problem, and why is it undecidable? Sketch the proof by contradiction.', 'theory-of-computation-decidability | pillar:CS Fundamentals', 'hard', 'research', '', 'https://climbtheladder.com/theory-of-computation-interview-questions/'),
    ('What is undefined behavior (UB) in C? Give three concrete examples and explain why the compiler is allowed — and often does — generate unexpected code around UB.', 'c-memory-model | pillar:CS Fundamentals', 'hard', 'research', 'Anthropic', 'https://www.geeksforgeeks.org/c/c-interview-questions/'),
    ("Describe C's memory layout for a running process: text, data, BSS, heap, and stack. What is placed in each segment, who manages it, and what errors arise from misuse?", 'c-memory-model | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://www.geeksforgeeks.org/c/pointers-and-dynamic-memory-allocation-interview-questions-c-programming/'),
    ('Describe the phases of a C compiler (preprocessing → lexing → parsing → semantic analysis → IR → optimization → code generation → linking). What does each phase produce, and what kind of error does each phase catch?', 'compilers-interpreters | pillar:CS Fundamentals', 'medium', 'research', '', 'https://www.vervecopilot.com/interview-questions/why-does-understanding-compiler-vs-interpreter-in-c-matter-so-much-in-technical-interviews'),
    ('What is the difference between a compiler, an interpreter, and a JIT compiler? Give one real-world example of each and explain the performance tradeoffs.', 'compilers-interpreters | pillar:CS Fundamentals', 'easy', 'ai-eng', '', 'https://www.vervecopilot.com/interview-questions/why-does-understanding-compiler-vs-interpreter-in-c-matter-so-much-in-technical-interviews'),
    ('Explain RAII (Resource Acquisition Is Initialization) in C++. Why is it the idiomatic solution to resource management, and how does it relate to smart pointers?', 'cpp-basics | pillar:CS Fundamentals', 'medium', 'research', '', 'https://www.golinuxcloud.com/c-and-cpp-interview-questions/'),
    ('What are the main inter-process communication (IPC) mechanisms in Linux? For each, describe its semantics and the appropriate use case.', 'operating-systems-ipc | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://codersnote.com/blog/os-interview-questions'),
    ('What is a Write-Ahead Log (WAL) and how does it guarantee durability? Explain how WAL enables crash recovery in PostgreSQL.', 'database-internals-wal | pillar:CS Fundamentals', 'hard', 'fde', '', 'https://skillsuites.com/storage-engine-internals/'),
    ('Explain the socket API call sequence for a TCP server and client. What does each syscall do, and what state does it create in the kernel?', 'computer-networks-sockets | pillar:CS Fundamentals', 'medium', 'fde', '', 'https://hyring.com/jobseeker-toolkit/interview-questions/technical/computer-networks'),
    ('Why is the Pumping Lemma useful, and how do you use it to prove that a given language is not regular? Demonstrate with L = {a^n b^n | n >= 1}.', 'theory-of-computation-automata | pillar:CS Fundamentals', 'hard', 'research', '', 'https://www.sanfoundry.com/automata-theory-interview-questions-answers-experienced/'),
    ('What inductive biases does a CNN bake in that a fully-connected network lacks, and why do those biases make CNNs efficient for images but potentially limiting for tasks requiring long-range context?', 'CNNs — receptive fields and inductive biases | pillar:Computer Vision & Multimodal', 'medium', 'ml', '', 'https://www.techinterview.org/post/3233460081/computer-vision-interview-questions-cnns-object-detection-and-transfer-learning'),
    ('Explain why residual (skip) connections in ResNet solve the degradation problem. What is the difference between the degradation problem and the vanishing-gradient problem, and does a residual connection fix both?', 'ResNet — residual connections | pillar:Computer Vision & Multimodal', 'medium', 'ml', '', 'https://www.techinterview.org/post/3233460081/computer-vision-interview-questions-cnns-object-detection-and-transfer-learning'),
    ('Walk through the Vision Transformer (ViT) architecture from a raw image to a classification output. Why does ViT underperform CNNs when trained on small datasets, and what architectural or training fixes address this?', 'Vision Transformers (ViT) — architecture and data hunger | pillar:Computer Vision & Multimodal', 'medium', 'ai-eng', '', 'https://huggingface.co/blog/RDTvlokip/when-transformers-invade-computer-vision'),
    ("A team is building a real-time defect detection system for a semiconductor fab. Training data is ~50k labeled images. Walk through whether you'd choose a CNN-based backbone, a ViT, or a hybrid, and justify the decision across accuracy, inference latency, and dataset size axes.", 'ViT vs CNN — production tradeoffs | pillar:Computer Vision & Multimodal', 'hard', 'fde', '', 'https://hiya31.medium.com/cnn-vs-vision-transformer-vit-which-wins-in-2025-e1cb2dfcb903'),
    ('Explain the role of anchor boxes in Faster R-CNN. What problem do anchors solve, and what problems do they themselves introduce? How do anchor-free detectors like FCOS address those drawbacks?', 'Object detection — anchor-based vs anchor-free | pillar:Computer Vision & Multimodal', 'hard', 'ml', '', 'https://www.techinterview.org/post/3233460081/computer-vision-interview-questions-cnns-object-detection-and-transfer-learning'),
    ('Describe how YOLO frames object detection as a single regression problem. What are the key architectural innovations from YOLOv1 to YOLOv10, and in what production scenarios does YOLO still beat transformer-based detectors?', 'YOLO — architecture and evolution | pillar:Computer Vision & Multimodal', 'medium', 'fde', '', 'https://www.datacamp.com/blog/top-machine-learning-interview-questions'),
    ("Explain DETR's end-to-end detection pipeline. What role do object queries play, why is Hungarian matching used during training, and what are DETR's main weaknesses compared to YOLO on a real-time inference budget?", 'DETR — transformer-based detection | pillar:Computer Vision & Multimodal', 'hard', 'ml', 'Meta', 'https://www.lightly.ai/blog/detr'),
    ('Design a real-time pedestrian detection and tracking system for a network of 500 traffic cameras feeding a city-wide traffic management dashboard. Latency budget: <200ms end-to-end per frame. Cover model selection, streaming ingestion, inference infra, tracking, and monitoring.', 'System design — real-time video object detection at scale | pillar:Computer Vision & Multimodal', 'hard', 'fde', '', 'https://codefinity.com/blog/Top-25-Questions-and-Answers-for-Computer-Vision-Engineer-Interview'),
    ("Compare triplet loss and ArcFace loss for training a face recognition embedding model. Why does triplet loss suffer from training instability, and how does ArcFace's additive angular margin formulation overcome it?", 'Metric learning — triplet loss vs ArcFace | pillar:Computer Vision & Multimodal', 'hard', 'ml', '', 'https://learnopencv.com/face-recognition-with-arcface'),
    ('You need to build a reverse image search system over 50 million product photos. Explain how you would use FAISS. What index type would you choose, what are the accuracy-speed tradeoffs, and how do you handle index updates when new products are added daily?', 'FAISS — approximate nearest neighbor image search | pillar:Computer Vision & Multimodal', 'hard', 'fde', '', 'https://mayursurani.medium.com/ai-engineer-agentic-systems-technical-interview-playbook-5e589a32875d'),
    ('Explain how CLIP is trained and why contrastive loss produces a jointly aligned image-text embedding space. How would you use CLIP for zero-shot image classification, and what are its known failure modes?', 'CLIP — contrastive vision-language pretraining | pillar:Computer Vision & Multimodal', 'medium', 'ai-eng', 'OpenAI', 'https://www.geeksforgeeks.org/computer-vision/computer-vision-interview-questions'),
    ("Describe the architectural 'recipe' of LLaVA-style vision-language models: how is the visual encoder connected to the language model, what is the role of the projection/connector MLP, and how does Qwen2.5-VL improve over this baseline design?", 'VLM architecture — LLaVA / Qwen-VL internals | pillar:Computer Vision & Multimodal', 'hard', 'ai-eng', '', 'https://labelyourdata.com/articles/machine-learning/vision-language-models'),
    ("How do you evaluate a vision-language model for a production document understanding use case? Name at least three relevant benchmarks, explain what each measures, and describe what you would do when benchmark scores don't correlate with user satisfaction.", 'VLM evaluation — multimodal benchmarks | pillar:Computer Vision & Multimodal', 'medium', 'ai-eng', '', 'https://aman.ai/primers/ai/VLM'),
    ('Describe the stages of a production OCR pipeline for processing scanned invoices in multiple languages. Where does the pipeline commonly fail, and how do you improve accuracy for degraded/skewed/low-resolution inputs?', 'OCR pipelines — design and failure modes | pillar:Computer Vision & Multimodal', 'medium', 'fde', '', 'https://www.golem15.com/en/blog/ai-engineering/ai-document-processing-pipeline'),
    ('Explain what makes LayoutLM different from a standard BERT for document understanding tasks. What three input modalities does LayoutLMv3 jointly encode, and what pre-training objectives does it use?', 'LayoutLM — document AI model family | pillar:Computer Vision & Multimodal', 'hard', 'ai-eng', 'Microsoft', 'https://www.ankursnewsletter.com/p/what-is-intelligent-document-processing'),
    ('Design a production IDP pipeline to process 10,000 invoices per day from 200+ vendor templates with varying layouts. Cover model selection, confidence routing, human-in-the-loop, and how you measure and improve pipeline accuracy over time.', 'IDP system design — intelligent document processing architecture | pillar:Computer Vision & Multimodal', 'hard', 'fde', '', 'https://www.width.ai/post/what-is-intelligent-document-processing-idp'),
    ('How would you build a multimodal RAG system that answers questions over a corpus of 50,000 product manuals containing both text and diagrams? Walk through how you index, retrieve, and generate answers.', 'Multimodal RAG — image + text retrieval | pillar:Computer Vision & Multimodal', 'hard', 'ai-eng', '', 'https://huggingface.co/blog/vlms-2025'),
    ("You have a medical imaging classification task (chest X-ray: normal vs pneumonia vs COVID-19) with only 3,000 labeled images. Walk through your transfer learning strategy, which layers to freeze and unfreeze, and what augmentations you'd apply.", 'Transfer learning and fine-tuning for vision | pillar:Computer Vision & Multimodal', 'medium', 'ml', '', 'https://365datascience.com/career-advice/job-interview-tips/computer-vision-interview-questions'),
    ('Distinguish semantic segmentation, instance segmentation, and panoptic segmentation. For an autonomous vehicle perception stack, which task do you need and why? Name one model architecture for each.', 'Image segmentation — semantic vs instance vs panoptic | pillar:Computer Vision & Multimodal', 'medium', 'ml', '', 'https://www.geeksforgeeks.org/computer-vision/computer-vision-interview-questions'),
    ('A model trained on synthetic rendered images (GAN-generated or game engine) performs poorly when deployed on real camera images. What causes this synthetic-to-real domain gap, and what techniques can close it without re-collecting real labeled data?', 'Domain adaptation in vision models | pillar:Computer Vision & Multimodal', 'hard', 'research', 'DeepMind', 'https://www.techinterview.org/post/3233460081/computer-vision-interview-questions-cnns-object-detection-and-transfer-learning'),
    ('What is self-supervised learning in vision (SSL), how does DINO / DINOv2 train a ViT without labels, and what downstream tasks benefit most from DINOv2 features compared to supervised ImageNet pretraining?', 'DINO / DINOv2 — self-supervised vision features | pillar:Computer Vision & Multimodal', 'hard', 'research', 'Meta', 'https://huggingface.co/blog/RDTvlokip/when-transformers-invade-computer-vision'),
    ('What is object hallucination in vision-language models, how is it measured, and what techniques reduce it in a production VLM pipeline?', 'VLM hallucination — object hallucination in multimodal models | pillar:Computer Vision & Multimodal', 'hard', 'ai-eng', 'Anthropic', 'https://aman.ai/primers/ai/VLM'),
    ('You are building a visual similarity engine for an e-commerce catalog (fashion + furniture). Compare at least three embedding models you would evaluate, explain how you would measure retrieval quality offline, and describe how you would handle the cold-start problem for new product images.', 'Image embeddings — model choice and evaluation | pillar:Computer Vision & Multimodal', 'medium', 'fde', 'CARS24', 'https://www.datainterview.com/blog/ai-engineer-interview-prep'),
    ('A conv layer has 3 input channels, 64 output filters, and a 3×3 kernel with no bias. How many parameters does it have? If you increase kernel size to 5×5 with the same config, how do parameters change? What does this tell you about the efficiency of stacking 3×3 kernels vs using a single 5×5?', 'CNN parameter counting and efficiency | pillar:Computer Vision & Multimodal', 'easy', 'ml', '', 'https://www.techinterview.org/post/3233460081/computer-vision-interview-questions-cnns-object-detection-and-transfer-learning'),
    ('Explain how non-maximum suppression (NMS) works in object detection post-processing. What is its computational complexity, why is it a bottleneck in crowded scenes, and what alternatives exist?', 'Non-maximum suppression (NMS) | pillar:Computer Vision & Multimodal', 'medium', 'ml', '', 'https://medium.com/@faheemrustamy/detection-transformer-detr-vs-yolo-for-object-detection-baeb3c50bc3'),
    ('You are deploying a VLM (7B parameters) for real-time document Q&A at a fintech. Each query includes a page image and a user question; P95 latency must be under 2 seconds. Walk through model compression and serving strategies to hit this target.', 'Multimodal model — deployment and latency optimization | pillar:Computer Vision & Multimodal', 'hard', 'fde', '', 'https://labelyourdata.com/articles/machine-learning/vision-language-models'),
    ("Explain OpenAI Whisper's architecture. What is the encoder-decoder setup, what training objective does it use, and why does Whisper hallucinate on silence or long-form audio?", 'ASR Architecture — Whisper | pillar:Indic & Speech AI', 'medium', 'ai-eng', '', 'https://openai.com/index/whisper/'),
    ('What is the Conformer architecture and why does it outperform a pure Transformer for ASR? Where in the architecture is the CNN block placed, and what inductive bias does it inject?', 'ASR Architecture — Conformer | pillar:Indic & Speech AI', 'medium', 'ai-eng', '', 'https://www.speechdata.ai/blog/best-asr-models-2026'),
    ('Compare CTC, RNN-T, and attention encoder-decoder (AED) as ASR output heads. What are the independence assumption, streaming capability, and language-model integration differences?', 'CTC vs RNN-T vs AED Decoding | pillar:Indic & Speech AI', 'hard', 'ai-eng', '', 'https://apxml.com/courses/speech-recognition-synthesis-asr-tts/chapter-2-advanced-acoustic-modeling-asr/rnn-transducer-asr'),
    ('Walk through the step-by-step computation of MFCCs from raw audio. Why is the mel scale used instead of a linear frequency axis, and what information is lost after the DCT step?', 'MFCC Feature Extraction | pillar:Indic & Speech AI', 'medium', 'ml', '', 'https://www.geeksforgeeks.org/nlp/mel-frequency-cepstral-coefficients-mfcc-for-speech-recognition/'),
    ('When would you prefer a log-mel spectrogram over MFCCs as the input feature for a modern ASR model? What has changed architecturally that made this shift happen?', 'Mel Spectrogram vs MFCC | pillar:Indic & Speech AI', 'easy', 'ml', '', 'https://learnopencv.com/automatic-speech-recognition/'),
    ('What is Voice Activity Detection and where is it used in a production ASR or diarization pipeline? What are the failure modes of energy-based VAD versus a neural VAD?', 'Voice Activity Detection (VAD) | pillar:Indic & Speech AI', 'medium', 'fde', '', 'https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/asr/speaker_diarization/intro.html'),
    ('Describe the end-to-end pipeline of a cascaded speaker diarization system. What is the role of speaker embeddings (x-vectors / d-vectors) and how does clustering assign speakers?', 'Speaker Diarization Pipeline | pillar:Indic & Speech AI', 'hard', 'ai-eng', '', 'https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/asr/speaker_diarization/intro.html'),
    ('Design a real-time multilingual ASR service supporting 10 Indian languages at p95 latency < 300 ms for a call-center platform. Cover model choice, streaming, batching, and latency budget.', 'ASR System Design — Low-Latency Multilingual | pillar:Indic & Speech AI', 'hard', 'fde', 'Sarvam', 'https://caller.digital/blog/open-source-voice-ai-india-sarvam-ai4bharat-bhasini-2026'),
    ('Compare a traditional TTS pipeline (text normalization → acoustic model → vocoder) with an end-to-end TTS (e.g., VITS / NaturalSpeech). What are the MOS and speaker-similarity tradeoffs?', 'Text-to-Speech Systems | pillar:Indic & Speech AI', 'medium', 'ai-eng', 'AI4Bharat', 'https://arxiv.org/html/2409.05356v2'),
    ('What is IndicSUPERB and how is it structured? What did the Shrutilipi dataset contribute, and what WER improvements were observed when it was added to Wav2Vec2 training for Hindi?', 'Indic ASR Benchmarks — IndicSUPERB & Shrutilipi | pillar:Indic & Speech AI', 'medium', 'research', 'AI4Bharat', 'https://arxiv.org/abs/2208.11761'),
    ("What is the 'token fertility' problem for Indic languages in LLMs, and how does it affect inference cost and model quality? What approaches mitigate it?", 'Indic Tokenization — Token Fertility Problem | pillar:Indic & Speech AI', 'hard', 'research', 'Sarvam', 'https://arxiv.org/pdf/2407.12481'),
    ('Explain the technique of continued pretraining (CPT) for extending an English LLM to Indic languages. What are the key risks, and what data mixture strategy works best?', 'Continued Pretraining for Indic Languages | pillar:Indic & Speech AI', 'hard', 'research', 'Sarvam', 'https://arxiv.org/html/2407.12481v1'),
    ("What is the architectural difference between IndicBERT and IndicBART? For which tasks would you use each, and what is IndicBART's strategy for handling script diversity?", 'IndicBERT and IndicBART | pillar:Indic & Speech AI', 'medium', 'research', 'AI4Bharat', 'https://arxiv.org/abs/2109.02903'),
    ('How does IndicTrans2 achieve state-of-the-art translation across all 22 scheduled Indian languages? What is the BPCC corpus and what training strategy is used?', 'Machine Translation — IndicTrans2 | pillar:Indic & Speech AI', 'hard', 'research', 'AI4Bharat', 'https://medium.com/@raju.kandasamy/from-english-to-indic-leveraging-indictrans2-for-nlp-and-indic-llm-2b6164457de1'),
    ('What is Bhashini and how does it function as a Digital Public Infrastructure? What APIs does it expose, and how does it relate to AI4Bharat and Sarvam AI models?', 'Bhashini Ecosystem | pillar:Indic & Speech AI', 'easy', 'fde', 'Sarvam', 'https://analyticsindiamag.com/ai-features/bhashini-ai4bharat-and-sarvam-might-finally-solve-indias-language-divide/'),
    ('What is code-switching and why is it a hard problem for NLP systems trained on monolingual data? Enumerate the distinct linguistic phenomena that make Hinglish particularly challenging.', 'Code-Switching — Hinglish NLP | pillar:Indic & Speech AI', 'medium', 'research', 'Sarvam', 'https://arxiv.org/html/2510.07037v6'),
    ('What is the difference between transliteration and translation in the context of Indic NLP? When does a system need both, and what tools does the AI4Bharat ecosystem provide?', 'Transliteration vs Translation | pillar:Indic & Speech AI', 'easy', 'ai-eng', 'AI4Bharat', 'https://aclanthology.org/2022.wmt-1.113.pdf'),
    ('What models has Sarvam AI released and what distinguishes Sarvam-1 from Sarvam-M? What is the strategic significance of the IndiaAI Mission selection in April 2025?', 'Sarvam AI — Models and IndiaAI Mission | pillar:Indic & Speech AI', 'easy', 'fde', 'Sarvam', 'https://en.wikipedia.org/wiki/Sarvam_AI'),
    ('You are tasked with fine-tuning Whisper large-v3 on a 500-hour Hindi call-center dataset to reduce WER from 18% to below 10%. Describe your complete fine-tuning strategy, evaluation setup, and known pitfalls.', 'Fine-tuning Whisper for Indic ASR | pillar:Indic & Speech AI', 'hard', 'ai-eng', 'Sarvam', 'https://arxiv.org/pdf/2606.17662'),
    ('Why is Word Error Rate (WER) an inadequate metric for evaluating ASR systems on morphologically rich Indic languages, and what alternative metrics should be used?', 'WER vs CER for Indic Languages | pillar:Indic & Speech AI', 'medium', 'ml', '', 'https://arxiv.org/abs/2208.11761'),
    ('Explain the self-supervised pretraining objective of wav2vec 2.0. How does it handle the lack of labeled speech data, and how is it used for low-resource Indic ASR?', 'Self-Supervised Speech Models — wav2vec 2 and HuBERT | pillar:Indic & Speech AI', 'hard', 'research', 'AI4Bharat', 'https://www.speechdata.ai/blog/best-asr-models-2026'),
    ('What are End-to-End Neural Diarization (EEND) models and how do they differ from cascaded systems? What is the EEND-EDA extension and why is it needed?', 'End-to-End vs Cascaded Diarization | pillar:Indic & Speech AI', 'hard', 'research', '', 'https://arxiv.org/pdf/2305.18074'),
    ('Describe SpecAugment and explain why it is the most widely used augmentation technique for ASR. What does it augment, and how does it improve WER?', 'SpecAugment and Data Augmentation for ASR | pillar:Indic & Speech AI', 'medium', 'ml', '', 'https://learnopencv.com/automatic-speech-recognition/'),
    ('For a multilingual Indic LLM covering Devanagari, Tamil, and Telugu scripts, should you use BPE or Unigram LM tokenization? Justify with reference to morphological richness and fertility.', 'Subword Tokenization for Indic Scripts — BPE vs Unigram | pillar:Indic & Speech AI', 'hard', 'research', 'Sarvam', 'https://arxiv.org/pdf/2508.08424'),
    ('Why is BLEU an inadequate metric for evaluating machine translation into morphologically rich Indic languages? What alternatives exist, and what does IndicTrans2 use?', 'Evaluation Metrics for Machine Translation | pillar:Indic & Speech AI', 'medium', 'research', 'AI4Bharat', 'https://aclanthology.org/2022.findings-acl.145.pdf'),
    ('What is Grapheme-to-Phoneme (G2P) conversion and why is it harder for Indic languages than English? How do Devanagari and Dravidian scripts differ in their G2P regularity?', 'G2P and TTS for Indic Languages | pillar:Indic & Speech AI', 'medium', 'ai-eng', 'AI4Bharat', 'https://arxiv.org/html/2409.05356v2'),
    ('A call-center ASR system deployed on real IVR audio shows 30% WER despite a 12% WER on the clean test set. What are the likely causes and how would you systematically debug and improve it?', 'ASR for Noisy Call-Center Audio | pillar:Indic & Speech AI', 'hard', 'fde', '', 'https://arxiv.org/pdf/2606.17662'),
    ('For a production voice assistant in Indian languages requiring < 200 ms first-word latency, compare deploying Whisper large-v3 vs a Conformer-RNN-T model. Which would you choose and why?', 'Conformer vs Whisper for Production Streaming | pillar:Indic & Speech AI', 'hard', 'fde', 'Sarvam', 'https://www.speechdata.ai/blog/best-asr-models-2026'),
    ('How would you build a spoken language identification (LID) system that can distinguish between 10 Indian languages in a multilingual call-center? What features and architectures are used?', 'Language Identification for Indic Speech | pillar:Indic & Speech AI', 'medium', 'ai-eng', '', 'https://caller.digital/blog/open-source-voice-ai-india-sarvam-ai4bharat-bhasini-2026'),
    ('Explain the memory fragmentation problem in naive LLM inference and describe how PagedAttention solves it. What OS concept does it borrow from, and what is the concrete throughput benefit in practice?', 'PagedAttention & KV Cache | pillar:GenAI/ML Engineering Stack', 'medium', 'ai-eng', 'vLLM / NVIDIA', 'https://www.runpod.io/articles/guides/vllm-pagedattention-continuous-batching'),
    ('What is continuous batching (iteration-level scheduling) in LLM serving, and how does it differ from static batching? Under what request-length distributions does it most help, and what is the downside?', 'Continuous Batching | pillar:GenAI/ML Engineering Stack', 'medium', 'ai-eng', '', 'https://www.spheron.network/blog/llm-serving-optimization-continuous-batching-paged-attention'),
    ('Derive the GPU memory required for the KV cache of a LLaMA-3-70B model (GQA, 8 KV heads, head_dim=128, 80 layers) serving a batch of 8 requests each with a 32K-token context in FP16. What changes if you quantize the KV cache to FP8?', 'KV Cache Memory Math | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'NVIDIA / Anthropic', 'https://fahimfaisal.info/ml_and_llm_learning/69_ai_infrastructure_engineering/AI_INFRA_ENGINEER_PLAYBOOK.html'),
    ("Explain speculative decoding: what problem does it solve, what are the two models involved, and why is the acceptance step correct (i.e., why doesn't it introduce distributional error in the outputs)? What governs the speedup?", 'Speculative Decoding | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'Anthropic / DeepMind', 'https://theorempath.com/topics/speculative-decoding-and-quantization'),
    ("Compare GPTQ, AWQ, and FP8 quantization for production LLM serving. What is each method's core technique, what precision does it target, what hardware best supports it, and what are the accuracy failure modes to watch for?", 'Quantization: GPTQ vs AWQ vs FP8 | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'NVIDIA / Together AI', 'https://www.calibreos.com/blog/genai-llm-serving-inference-interview-guide'),
    ('LLM inference has two phases: prefill and decode. Explain why they have opposite bottlenecks, how chunked prefill addresses the interference problem on a single node, and when you would instead use full prefill-decode disaggregation. What are the infrastructure costs of disaggregation?', 'Prefill vs Decode Disaggregation | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'vLLM / SGLang', 'https://medium.com/@milesk_33/prefill-vs-decode-phase-the-hidden-latency-bottleneck-in-llm-inference-089906037fb8'),
    ('You need to deploy a LLaMA-3-70B model serving 200 concurrent requests at P99 TTFT < 3s and TPOT < 80ms on NVIDIA H100s. Walk through your framework choice decision between vLLM, TensorRT-LLM, and SGLang, and describe what configuration parameters matter most.', 'vLLM vs TensorRT-LLM | pillar:GenAI/ML Engineering Stack', 'hard', 'fde', 'NVIDIA / Deployment Inc', 'https://www.runpod.io/articles/guides/vllm-pagedattention-continuous-batching'),
    ("Explain CUDA's memory hierarchy (registers, shared memory, L1/L2 cache, global HBM). What is memory coalescing, why does uncoalesced access hurt throughput so severely, and how would you diagnose and fix a coalescing problem in a custom attention kernel?", 'CUDA Memory Hierarchy & Coalescing | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'NVIDIA', 'https://huru.ai/nvidia-interview-questions-mastering-cuda-inference-systems'),
    ('What problem does FlashAttention solve that standard attention does not, and what algorithmic technique does it use? How does it relate to memory bandwidth, and why does it matter for both training and inference?', 'FlashAttention | pillar:GenAI/ML Engineering Stack', 'hard', 'research', 'Anthropic / DeepMind', 'https://www.calibreos.com/blog/genai-llm-serving-inference-interview-guide'),
    ('Explain tensor parallelism for LLM inference. How is a transformer layer split across N GPUs, what collective operations are required, and what is the latency overhead? How does it differ from pipeline parallelism, and when does each make sense for inference?', 'Tensor Parallelism & Model Sharding | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'NVIDIA / Sarvam AI', 'https://www.indeed.com/viewjob?jk=35edb76f909f429d'),
    ('Define TTFT, TPOT, and ITL. How do you set SLOs for an LLM API serving a mix of chat (interactive) and batch summarization workloads? If your P99 TTFT degrades but P50 is fine, what is the most likely cause and how do you fix it?', 'Inference Serving Metrics & SLOs | pillar:GenAI/ML Engineering Stack', 'medium', 'fde', 'CARS24 / Deployment Inc', 'https://www.spheron.network/blog/prefill-decode-disaggregation-gpu-cloud'),
    ("What is warp divergence in CUDA, how does it reduce GPU efficiency, and what are two concrete coding patterns that cause it in ML kernels? What does 'occupancy' mean and how do you increase it?", 'Warp Divergence & Occupancy | pillar:GenAI/ML Engineering Stack', 'hard', 'ai-eng', 'NVIDIA', 'https://extrabrain.app/interview-questions/nvidia-deep-learning-interview-extrabrain'),
    ('What is training-serving skew, how does it manifest in production ML systems, and what are the three most effective architectural safeguards against it? Give a concrete example involving a feature store.', 'Training-Serving Skew | pillar:MLOps & LLMOps', 'medium', 'ml', 'Amazon', 'https://myinternships.in/aws-interview-questions/sagemaker-and-ai'),
    ('Design the CI/CD pipeline for a production ML model. What gates must pass before a new model artifact is promoted to production? How does it differ from a standard software CI/CD pipeline?', 'ML CI/CD Pipeline | pillar:MLOps & LLMOps', 'hard', 'ml', 'Google / Meta', 'https://crackmlinterview.com/guides/mlops-interview-questions-guide'),
    ('Distinguish data drift, concept drift, and model drift. For each, describe a statistical test or metric you would monitor in production and the automated action it should trigger.', 'Model Drift & Monitoring | pillar:MLOps & LLMOps', 'medium', 'ml', '', 'https://mentorcruise.com/questions/mlops'),
    ('You have a weekly model retraining pipeline: fetch new data from S3, run feature engineering with PySpark on EMR, train a model on SageMaker, evaluate it, register it if it passes, and deploy. Design this as an Airflow DAG and describe how you handle partial failures and idempotency.', 'Airflow for ML Pipelines | pillar:MLOps & LLMOps', 'medium', 'ml', 'Amazon', 'https://www.youtube.com/watch?v=RJAZPZUq-J0'),
    ('A PySpark job on a 500 GB dataset runs for 3 hours and you suspect data skew. How do you diagnose it, and what are three concrete remediation strategies? Why should you avoid PySpark UDFs and what are the alternatives?', 'Spark/PySpark Performance | pillar:MLOps & LLMOps', 'medium', 'ds', 'Databricks / Gartner', 'https://datavidhya.com/blog/apache-spark-data-engineering-interview-questions'),
    ('Describe how you would deploy and autoscale an LLM inference service on Kubernetes. What Kubernetes primitives are involved, and what metric drives the HPA? What specific challenges does LLM serving introduce compared to a standard stateless web service?', 'Kubernetes for ML Serving | pillar:MLOps & LLMOps', 'hard', 'fde', 'Google / Sarvam AI', 'https://mentorcruise.com/questions/mlops'),
    ('What is a model registry, what metadata should it capture, and how does it differ from experiment tracking? Describe a model promotion workflow from experiment → staging → production with rollback.', 'Model Registry & Versioning | pillar:MLOps & LLMOps', 'medium', 'ml', 'Amazon', 'https://crackmlinterview.com/guides/mlops-interview-questions-guide'),
    ('Explain the four SageMaker inference endpoint types (real-time, serverless, asynchronous, batch transform). When would you choose each, and what are the cost implications for a model called 3,000 times/day with high variance in payload size?', 'AWS SageMaker Serving | pillar:MLOps & LLMOps', 'medium', 'fde', 'Amazon', 'https://myinternships.in/aws-interview-questions/sagemaker-and-ai'),
    ('You deploy an LLM-powered product in production. Beyond standard infrastructure metrics (latency, error rate), what LLM-specific signals do you monitor, and what does each catch? Describe how you would detect model version drift when the underlying API provider silently updates the model.', 'LLMOps: Prompt & Output Monitoring | pillar:MLOps & LLMOps', 'medium', 'ai-eng', 'Anthropic / OpenAI', 'https://fahimfaisal.info/ml_and_llm_learning/69_ai_infrastructure_engineering/AI_INFRA_ENGINEER_PLAYBOOK.html'),
    ('A model trained 6 months ago needs to be re-trained exactly for a regulatory audit. Walk through every layer of the system you need to lock down to guarantee the same model artifact. What is the most commonly overlooked source of non-reproducibility?', 'Reproducibility in ML | pillar:MLOps & LLMOps', 'medium', 'ml', '', 'https://crackmlinterview.com/guides/mlops-interview-questions-guide'),
    ('Describe the difference between shadow deployment and canary deployment for an ML model. When is each appropriate, and what metric thresholds would you use to decide whether to roll a canary forward or trigger automatic rollback?', 'Shadow & Canary Deployment | pillar:MLOps & LLMOps', 'hard', 'ml', 'Meta / Google', 'https://crackmlinterview.com/guides/mlops-interview-questions-guide'),
    ('Explain the difference between narrow and wide transformations in Spark, how they determine stage boundaries, and how they affect shuffle. Give two examples of each and describe an optimization pattern that converts a wide transformation into a narrow one.', 'PySpark Narrow vs Wide Transformations | pillar:MLOps & LLMOps', 'medium', 'ds', 'Databricks', 'https://www.igmguru.com/blog/pyspark-interview-questions'),
    ('You are building a customer-facing LLM application on AWS using Amazon Bedrock. A Bedrock-based Lambda + API Gateway stack has P95 latency spikes and intermittent throttling during traffic bursts. Describe a hardened architecture that handles scale and operational reliability without changing the model or prompts.', 'AWS Bedrock & Guardrails | pillar:MLOps & LLMOps', 'hard', 'fde', 'Amazon', 'https://www.datainterview.com/blog/amazon-ai-engineer-interview'),
    ('What is NVIDIA Triton Inference Server and how does it differ from vLLM? Describe the model repository layout, the key backend types, and how dynamic batching works in Triton for a transformer model.', 'Triton Inference Server | pillar:GenAI/ML Engineering Stack', 'medium', 'fde', 'NVIDIA', 'https://huru.ai/nvidia-interview-questions-mastering-cuda-inference-systems'),
    ('Explain the superposition hypothesis in neural networks. Why does it arise, and what does it imply for mechanistic interpretability?', 'mechanistic-interpretability-superposition | pillar:Research & Frontier', 'medium', 'research', 'Anthropic', 'https://transformer-circuits.pub/2022/toy_model/index.html'),
    ('What are Sparse Autoencoders (SAEs) in mechanistic interpretability, and how do they address the polysemanticity problem? What is the key training objective?', 'mechanistic-interpretability-SAEs | pillar:Research & Frontier', 'hard', 'research', 'Anthropic', 'https://transformer-circuits.pub/2025/july-update/index.html'),
    ("What is a 'circuit' in a transformer, and how are circuits discovered? Describe the induction head circuit as a concrete example.", 'mechanistic-interpretability-circuits | pillar:Research & Frontier', 'hard', 'research', 'Anthropic', 'https://transformer-circuits.pub/2022/in-context-learning-and-induction-heads/index.html'),
    ('Name three open problems in mechanistic interpretability as of 2025-2026 and explain why each is hard.', 'mechanistic-interpretability-open-problems | pillar:Research & Frontier', 'hard', 'research', '', 'https://arxiv.org/pdf/2511.19265'),
    ('Explain the core innovation of Mamba compared to prior SSMs like S4. What is the selective scan mechanism and why does it matter?', 'mamba-ssm-architecture | pillar:Research & Frontier', 'hard', 'research', '', 'https://arxiv.org/html/2408.01129v8'),
    ('Compare Mamba (SSM) and a Transformer on: (a) time complexity for training vs inference, (b) handling of long-range dependencies, (c) known weaknesses.', 'mamba-vs-transformer | pillar:Research & Frontier', 'medium', 'research', '', 'https://arxiv.org/html/2503.18970v2'),
    ('Why must continuous-time SSMs be discretized before use in deep learning, and what is Zero-Order Hold (ZOH) discretization?', 'ssm-discretization | pillar:Research & Frontier', 'hard', 'research', '', 'https://arxiv.org/html/2503.18970v2'),
    ('Contrast RLHF and RLVR. When is RLVR applicable, and what makes its reward signal qualitatively different?', 'rlvr-vs-rlhf | pillar:Research & Frontier', 'medium', 'research', 'DeepMind', 'https://www.turingpost.com/p/stateofrl2025'),
    ('Explain GRPO (Group Relative Policy Optimization). How does it estimate advantages without a critic model, and what does this save computationally?', 'grpo-vs-ppo | pillar:Research & Frontier', 'hard', 'research', '', 'https://shivu-agr.medium.com/rl-for-llms-in-2026-from-ppo-to-dpo-to-grpo-to-multi-agent-rl-1c00e1dacba7'),
    ('Derive the DPO objective from first principles. What implicit reward model does DPO parameterize, and what assumptions does it rest on?', 'dpo-derivation | pillar:Research & Frontier', 'hard', 'research', '', 'https://shivu-agr.medium.com/rl-for-llms-in-2026-from-ppo-to-dpo-to-grpo-to-multi-agent-rl-1c00e1dacba7'),
    ('Distinguish Process Reward Models (PRMs) from Outcome Reward Models (ORMs) for reasoning. What are the practical trade-offs and which approach is currently dominant?', 'prm-vs-orm | pillar:Research & Frontier', 'medium', 'research', '', 'https://www.turingpost.com/p/reasoning-rl-in-2026'),
    ("Why does chain-of-thought reasoning 'emerge' from RL with verifiable rewards, rather than requiring explicit CoT supervision? What does DeepSeek-R1-Zero demonstrate?", 'reasoning-models-emergence | pillar:Research & Frontier', 'hard', 'research', '', 'https://www.turingpost.com/p/reasoning-rl-in-2026'),
    ('State the Chinchilla scaling law. What did Hoffmann et al. (2022) find about prior model training regimes, and what is the practical compute-optimal training recipe?', 'scaling-laws-chinchilla | pillar:Research & Frontier', 'hard', 'research', 'DeepMind', 'https://medium.com/@siddantvardey/the-frontier-reasoning-models-scaling-laws-whats-actually-coming-next-93bba260644b'),
    ('Scaling laws originally governed pre-training compute. How has the notion of scaling evolved with inference-time compute (test-time scaling)? What is the key tradeoff?', 'scaling-laws-inference-vs-pretraining | pillar:Research & Frontier', 'medium', 'research', '', 'https://medium.com/@siddantvardey/the-frontier-reasoning-models-scaling-laws-whats-actually-coming-next-93bba260644b'),
    ('Explain the Mixture-of-Experts (MoE) architecture for transformers. What does it change in the FFN layer, and what is the key training challenge?', 'mixture-of-experts | pillar:Research & Frontier', 'medium', 'research', '', 'https://arxiv.org/pdf/2601.08215'),
    ('How do Chinchilla-style scaling laws need to be modified for MoE models? What parameter count should be used when fitting MoE laws?', 'moe-scaling-laws | pillar:Research & Frontier', 'hard', 'research', '', 'https://arxiv.org/pdf/2502.05172'),
    ('What are looped (recurrent-depth) transformers? Why do they outperform parameter-matched standard transformers on reasoning tasks, and what is the SMELT finding?', 'looped-transformers | pillar:Research & Frontier', 'hard', 'research', '', 'https://arxiv.org/html/2609.01343v1'),
    ("Describe LeCun's JEPA (Joint Embedding Predictive Architecture). How does it differ from generative models like diffusion or autoregressive LMs, and what problem does it aim to solve?", 'jepa-world-models | pillar:Research & Frontier', 'medium', 'research', '', 'https://www.taskade.com/blog/ai-world-models'),
    ('How does a world model enable planning in an agent, and what is the connection to model-based reinforcement learning (MBRL)?', 'world-models-planning | pillar:Research & Frontier', 'medium', 'research', '', 'https://arxiv.org/pdf/2411.07690'),
    ('What is reward hacking, and why is it a fundamental alignment problem? Give two concrete examples and describe mitigation strategies.', 'ai-safety-reward-hacking | pillar:Research & Frontier', 'medium', 'research', 'Anthropic', 'https://arxiv.org/pdf/2604.13602'),
    ('Explain Constitutional AI (CAI). How does it differ from standard RLHF, and why might it scale better as models become more capable?', 'constitutional-ai | pillar:Research & Frontier', 'medium', 'research', 'Anthropic', 'https://www.techinterview.org/post/3233460267/anthropic-interview-guide-2026-process-questions-and-ai-safety/'),
    ('What is the scalable oversight problem in AI safety? Describe two proposed approaches (debate and recursive reward modeling) and their core assumptions.', 'scalable-oversight | pillar:Research & Frontier', 'hard', 'research', 'DeepMind', 'https://arxiv.org/pdf/2505.03989'),
    ("What is emergent misalignment in RL-trained LLMs? Describe the 'sycophancy to subterfuge' spectrum and why it is concerning for deployed systems.", 'emergent-misalignment | pillar:Research & Frontier', 'hard', 'research', 'Anthropic', 'https://arxiv.org/pdf/2511.18397'),
    ('From a deployment and systems engineering perspective, what are the practical trade-offs of serving a MoE model vs a dense model of equivalent active-parameter count?', 'moe-vs-dense-deployment | pillar:Research & Frontier', 'medium', 'ai-eng', '', 'https://arxiv.org/pdf/2601.08215'),
    ('How does mechanistic interpretability connect to AI safety goals? Give two concrete safety applications where circuit-level understanding would be directly useful.', 'mechanistic-interp-safety-connection | pillar:Research & Frontier', 'hard', 'research', 'Anthropic', 'https://intuitionlabs.ai/articles/mechanistic-interpretability-ai-llms'),
    ('LeCun argues that autoregressive LLMs cannot be the path to AGI. Summarize his core arguments and the strongest counterarguments.', 'jepa-vs-llm-critique | pillar:Research & Frontier', 'medium', 'research', '', 'https://www.optim.vc/catching-up-on-yann-lecun-jepa-world-models-ami-labs-and-the-war-against-llms/'),
    ("Recent research shows RLVR makes models more 'efficient' but reduces reasoning 'range'. What does this mean and what are the implications for model training?", 'rlvr-limitations | pillar:Research & Frontier', 'hard', 'research', '', 'https://arxiv.org/pdf/2603.22117'),
    ('How does data quality interact with scaling laws? What happens to the Chinchilla-optimal token count when you filter for high-quality data?', 'scaling-laws-data-quality | pillar:Research & Frontier', 'hard', 'research', '', 'https://medium.com/@siddantvardey/the-frontier-reasoning-models-scaling-laws-whats-actually-coming-next-93bba260644b'),
    ('You are building an interpretability pipeline to understand what features a specific MLP layer in a 7B transformer encodes. Walk through the design: data, training objective, evaluation, and limitations.', 'superposition-saes-interview-system-design | pillar:Research & Frontier', 'hard', 'research', 'Anthropic', 'https://arxiv.org/pdf/2503.05613'),
    ('What is the difference between __str__ and __repr__ in Python? When should each be implemented, and what happens if only one is defined?', 'python-data-model-dunder | pillar:Software Engineering', 'easy', 'fde', '', 'https://www.datacamp.com/blog/top-python-interview-questions-and-answers'),
    ('Explain how __eq__ and __hash__ are linked in Python. What is the contract, and what breaks when you violate it?', 'python-data-model-dunder | pillar:Software Engineering', 'medium', 'fde', '', 'https://netalith.com/blogs/career-hiring/oop-in-python-essential-interview-questions-2026'),
    ("How does Python's __new__ differ from __init__? Give a concrete use case where you must override __new__ rather than __init__.", 'python-data-model-dunder | pillar:Software Engineering', 'medium', 'fde', '', 'https://pynative.com/python-oop-interview-questions/'),
    ('Implement a class Vector2D that supports +, *, ==, abs(), and repr(). What dunder methods does each operation require?', 'python-data-model-dunder | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.datacamp.com/blog/top-python-interview-questions-and-answers'),
    ('A codebase has a UserManager class that handles authentication, sends welcome emails, writes audit logs, and queries the user DB. Which SOLID principle does this violate, and how would you refactor it?', 'python-oop-design | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.interviewbit.com/oops-interview-questions/'),
    ('Explain the Liskov Substitution Principle with the classic Square-extends-Rectangle example. Why does it fail, and how do you fix the design?', 'python-oop-design | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.geeksforgeeks.org/interview-prep/oops-interview-questions/'),
    ("What is the Dependency Inversion Principle and how does Python's duck typing partially address it without explicit interfaces? Give an example with a notification system.", 'python-oop-design | pillar:Software Engineering', 'hard', 'fde', '', 'https://www.qfles.com/interview-question/solid-principles-interview-questions'),
    ('Explain the GIL. Given a CPU-bound loop in Python, will spawning 8 threads use 8 cores? Why or why not, and what is the correct approach?', 'python-concurrency-gil | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.coprep.ai/blog/python-concurrency-interview-questions-2026'),
    ('When would you choose asyncio over threading for a Python service that makes 500 concurrent outbound HTTP calls? What breaks if you accidentally block the event loop?', 'python-concurrency-gil | pillar:Software Engineering', 'medium', 'ai-eng', 'Anthropic', 'https://medium.com/@anqi.silvia/the-actual-concurrency-questions-from-my-2025-anthropic-interview-0738b1738ab9'),
    ('What are asyncio.gather, asyncio.wait, and asyncio.create_task? How do they differ in error handling, cancellation, and when all tasks are needed vs some?', 'python-concurrency-gil | pillar:Software Engineering', 'hard', 'ai-eng', '', 'https://staskoltsov.medium.com/python-asyncio-interview-questions-answers-advanced-0bdb081520ba'),
    ('What is the difference between a generator and a regular function that returns a list? Why does a generator save memory, and when would you NOT use one?', 'python-generators-decorators | pillar:Software Engineering', 'easy', 'fde', '', 'https://www.techinterview.org/post/3233474450/python-interview-questions-2025-generators-decorators-async-await-type-hints-dataclasses-concurrency-gil-memory-management/'),
    ("Write a decorator that (a) logs the function name and arguments before calling, (b) logs the return value after, and (c) correctly preserves the wrapped function's __name__ and __doc__. Why does __name__ preservation matter?", 'python-generators-decorators | pillar:Software Engineering', 'medium', 'fde', '', 'https://digitaldefynd.com/IQ/advanced-python-interview-questions/'),
    ('Explain contextlib.contextmanager and ExitStack. When is ExitStack the right tool, and what is the risk of forgetting a finally around the yield in a @contextmanager?', 'python-generators-decorators | pillar:Software Engineering', 'hard', 'fde', '', 'https://www.quipoin.com/interview/python/context-managers'),
    ('Git stores everything as objects. Name the four object types, explain what each contains, and trace what happens under the hood when you run `git commit`.', 'git-internals | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.toptal.com/git/interview-questions'),
    ("What is the difference between git merge and git rebase? When should you never rebase, and what is the 'golden rule' of rebasing?", 'git-internals | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.geeksforgeeks.org/git/git-interview-questions-and-answers/'),
    ('What is a detached HEAD state in Git? How do you get into it, what is the risk, and how do you recover commits made in that state?', 'git-internals | pillar:Software Engineering', 'medium', 'fde', '', 'https://www.interviewbit.com/git-interview-questions/'),
    ("You are designing a REST API for a resource 'orders'. A client wants to cancel an order. Should the endpoint be POST /orders/{id}/cancel or PATCH /orders/{id} with body {status: 'cancelled'}? Defend your choice with HTTP semantics.", 'api-design | pillar:Software Engineering', 'medium', 'fde', '', 'https://blog.postman.com/api-design-interview-questions/'),
    ('Compare REST, GraphQL, and gRPC. You are building: (a) a public partner API, (b) a mobile app with 3 different screen layouts fetching user data, (c) 10 internal microservices talking at high throughput. Which do you pick for each and why?', 'api-design | pillar:Software Engineering', 'hard', 'ai-eng', '', 'https://www.designgurus.io/blog/rest-graphql-grpc-system-design'),
    ('What is API versioning? Describe at least three strategies (URI path, header, query param) and state the tradeoff of each. Which would you use for a public API and why?', 'api-design | pillar:Software Engineering', 'medium', 'fde', '', 'https://roadmap.sh/questions/rest-api'),
    ('Explain the test pyramid. In a data-science / AI engineering project, where do people typically over-invest and under-invest, and what is the consequence?', 'testing-strategy | pillar:Software Engineering', 'medium', 'ml', '', 'https://openskills.cc/skills/sickn33-skills-python-testing-patterns'),
    ('You have a function that calls an external payment API. Explain three different test strategies for it, and state when you would use each in a CI pipeline.', 'testing-strategy | pillar:Software Engineering', 'medium', 'fde', '', 'https://goodspace.ai/interview-questions/pytest'),
    ('What is pytest parametrize? Give a realistic example where it catches a bug that a single-case test would miss, and explain how it differs from a test fixture.', 'testing-strategy | pillar:Software Engineering', 'easy', 'fde', '', 'https://www.interviewbit.com/pytest-interview-questions/'),
    ("What is the difference between pip install -r requirements.txt and a lock file (poetry.lock / uv.lock)? Why does requirements.txt alone cause 'works on my machine' bugs in production?", 'dependency-and-packaging | pillar:Software Engineering', 'easy', 'fde', '', 'https://cuttlesoft.com/blog/2026/01/27/python-dependency-management-in-2026/'),
    ('Explain the role of pyproject.toml in modern Python packaging. What replaced setup.py/setup.cfg, and how does the build-backend field work?', 'dependency-and-packaging | pillar:Software Engineering', 'medium', 'fde', '', 'https://dasroot.net/posts/2026/01/python-packaging-best-practices-setuptools-poetry-hatch/'),
    ("Name five code smells from Fowler's catalogue and for each give: the symptom, why it is harmful, and the canonical refactoring technique.", 'clean-code-refactoring | pillar:Software Engineering', 'medium', 'fde', '', 'https://interviewprep.org/refactoring-interview-questions/'),
    ('What is the DRY principle and when does following it blindly create MORE coupling? Give a concrete example where duplication is the better choice.', 'clean-code-refactoring | pillar:Software Engineering', 'medium', 'fde', '', 'https://dev.to/lourdesyang1023/mastering-software-development-best-practices-top-interview-questions-and-answers-solid-kiss-1k5g'),
    ('You inherit a Python service with no tests. A critical bug needs fixing. Describe your strategy for safely refactoring it, step by step, without breaking existing behaviour.', 'clean-code-refactoring | pillar:Software Engineering', 'hard', 'fde', '', 'https://reliabilitywhisperer.substack.com/p/code-refactoring-interview-preparation'),
    ('Python 3.13 introduced a free-threaded build (no-GIL / PEP 703). What does this change, what does it NOT change, and what new classes of bugs does it introduce for code that was previously safe under the GIL?', 'python-concurrency-gil | pillar:Software Engineering', 'hard', 'ai-eng', '', 'https://www.coprep.ai/blog/python-concurrency-interview-questions-2026'),
    ('Design the pagination strategy for a REST API endpoint GET /posts that returns potentially millions of records. Compare offset pagination, cursor pagination, and keyset pagination. Which would you use for a real-time feed and why?', 'api-design | pillar:Software Engineering', 'hard', 'fde', '', 'https://www.designgurus.io/blog/rest-graphql-grpc-system-design'),
    ("Explain the three core rules of the Mom Test and why asking 'Would you pay $10/month for this?' is a bad validation question.", 'idea-validation-mom-test | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.koji.so/blog/mom-test-customer-interviews-2026'),
    ("You've just built an MVP and you want to validate whether you've achieved problem-market fit. Walk through your validation interview process end-to-end.", 'idea-validation-mom-test | pillar:Startup & Product', 'hard', 'fde', '', 'https://ideaproof.io/questions/validation-interview-questions'),
    ("What is the difference between a 'problem interview' and a 'solution interview'? When should you run each, and why does conflating them kill startups?", 'idea-validation-mom-test | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.koji.so/docs/startup-idea-validation-guide'),
    ('Define CAC, LTV, and the LTV:CAC ratio. What ratio is considered healthy, and what does a ratio below 1:1 mean operationally?', 'saas-metrics-unit-economics | pillar:Startup & Product', 'easy', 'ds', '', 'https://thesaaslibrary.com/saas-metrics-explained/'),
    ("A SaaS company has MRR of $500K, adds $80K new MRR per month, but has 5% monthly logo churn. Compute net MRR growth and explain the 'leaky bucket' problem.", 'saas-metrics-unit-economics | pillar:Startup & Product', 'medium', 'ds', '', 'https://gatilab.com/saas-metrics-explained-mrr-arr-churn-ltv-and-cac/'),
    ('What is Net Revenue Retention (NRR) and why do investors consider it the single most important SaaS metric? How does NRR above 100% change the growth story?', 'saas-metrics-unit-economics | pillar:Startup & Product', 'medium', 'ds', '', 'https://cfoptimizer.com/startup-faqs/saas-metrics/'),
    ('What is the CAC Payback Period and why is a payback period of 12 months or less considered critical for capital efficiency? How does it interact with churn?', 'saas-metrics-unit-economics | pillar:Startup & Product', 'hard', 'ds', '', 'https://www.hackingthecaseinterview.com/pages/saas-case-interview'),
    ("Explain the 'Rule of 40' for SaaS companies. A company has 45% YoY ARR growth but −10% EBITDA margin. Does it pass, and how should the founding team think about the tradeoff?", 'saas-metrics-unit-economics | pillar:Startup & Product', 'hard', 'ds', '', 'https://www.finmodelbuilder.com/blog/saas-metrics-guide.html'),
    ('Compare flat-rate, per-seat, usage-based, and value-based pricing models for SaaS. For a B2B AI inference API, which would you recommend and why?', 'pricing-business-models | pillar:Startup & Product', 'medium', 'fde', '', 'https://stripe.com/resources/more/saas-pricing-models-101'),
    ('A founder is deciding between freemium and a free trial for a new B2B productivity tool. Walk through the decision framework and the key metrics to watch.', 'pricing-business-models | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.getmonetizely.com/articles/freemium-vs-premium-saas-pricing-models-which-strategy-drives-better-business-outcomes'),
    ('Why does ProfitWell data show that a 1% improvement in pricing yields more profit than a 1% improvement in acquisition or retention? Derive the math intuition.', 'pricing-business-models | pillar:Startup & Product', 'hard', 'ds', '', 'https://www.planmysaas.com/guides/saas-pricing-strategy-guide'),
    ("What is the difference between a 'sales-led' and a 'product-led' GTM motion? For a data infrastructure tool with $80K ACV, which would you recommend and why?", 'gtm-distribution-traction | pillar:Startup & Product', 'medium', 'fde', '', 'https://arisegtm.com/blog/go-to-market-strategy-for-startups'),
    ('You are the first hire at an early-stage B2B AI startup. The founder asks you to identify the best traction channel. Walk through the Bullseye Framework.', 'gtm-distribution-traction | pillar:Startup & Product', 'hard', 'fde', '', 'https://pipeline.zoominfo.com/sales/go-to-market-interview'),
    ('Explain product-led growth (PLG) and how Calendly, Atlassian, and Dropbox each embedded virality into the product workflow rather than relying on marketing spend.', 'gtm-distribution-traction | pillar:Startup & Product', 'medium', 'fde', '', 'https://techcrunch.com/2021/04/08/bootstrapping-managing-product-led-growth-and-knowing-when-to-fundraise'),
    ("Write a positioning statement for an AI code-review tool targeting mid-stage B2B SaaS engineering teams using the 'For/Who/Our product/That/Unlike/We' framework. Then explain what makes a positioning statement testable.", 'positioning-messaging | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.sybill.ai/blogs/icp-guide'),
    ('What is the difference between a target market, an ICP (Ideal Customer Profile), and a buyer persona? Why do early-stage startups that skip the ICP step churn more customers?', 'positioning-messaging | pillar:Startup & Product', 'easy', 'fde', '', 'https://www.factors.ai/blog/icp-marketing-guide'),
    ('Why must the founder close the first 10–20 customers personally before hiring a sales rep? What specific artifacts should the founder produce before making the first sales hire?', 'founder-led-sales | pillar:Startup & Product', 'medium', 'fde', '', 'https://launchingmax.com/founder-led-sales-guide-startups/'),
    ('Describe the structure of an effective B2B discovery call. What questions reveal whether a prospect is in your ICP and has budget authority?', 'founder-led-sales | pillar:Startup & Product', 'hard', 'fde', '', 'https://twsales.com/founder-led-sales-icp/'),
    ('Compare bootstrapping vs. VC funding on four dimensions: control, speed, hiring, and exit options. For a niche B2B SaaS serving manufacturing companies in India, which path would you argue for and why?', 'bootstrapping | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.rho.co/blog/bootstrapping-vs-venture-capital'),
    ('What types of businesses bootstrap well versus require VC? Give three examples of each and explain the structural reason.', 'bootstrapping | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.sidetool.co/post/why-bootstrapping-beats-funding-in-2025-real-success-stories/'),
    ("Define a 'growth loop' and contrast it with a traditional AARRR funnel. Give two concrete growth loop examples for a B2B SaaS product.", 'growth-loops | pillar:Startup & Product', 'medium', 'fde', '', 'https://www.saastr.com/how-to-think-about-product-led-growth-bootstrapping-vs-vc-and-early-exits-with-saastr-ceo-and-founder-jason-lemkin'),
    ('What is a viral coefficient (K-factor)? If K = 0.8 for a product with 1000 initial users, how many total users result from one viral cycle? What K value produces exponential growth?', 'growth-loops | pillar:Startup & Product', 'hard', 'ds', '', 'https://calmops.com/indie-hackers/saas-metrics-mrr-churn-ltv-cac/'),
    ('You are a DS/AI engineer at a startup and the CEO asks you to build a churn prediction model. Beyond model accuracy, what business metrics and product feedback loops should the model plug into?', 'saas-metrics-unit-economics | pillar:Startup & Product', 'hard', 'ds', '', 'https://www.gainsight.com/essential-guide/product-management-metrics/enterprise-product-metrics/'),
    ("Explain the concept of a 'negative ICP'. Why is knowing who NOT to sell to equally important as knowing your ICP, and how does it affect unit economics?", 'gtm-distribution-traction | pillar:Startup & Product', 'medium', 'fde', '', 'https://orangeowl.marketing/gtm/30-questions-to-determine-icp/'),
    ("You are advising an early-stage AI startup that is charging $99/month flat-rate but a big customer wants enterprise pricing. Walk through the pricing conversation and what questions you'd ask before quoting.", 'pricing-business-models | pillar:Startup & Product', 'hard', 'fde', '', 'https://www.revenera.com/blog/software-monetization/saas-pricing-models-guide/'),]


def main(apply: bool) -> None:
    init_db()
    conn = connect()
    try:
        before = conn.execute("SELECT COUNT(*) AS n FROM questions").fetchone()["n"]
        print(f"questions before: {before}")
        print(f"rows defined:     {len(QUESTIONS)}")

        if not apply:
            existing = {r["question"] for r in conn.execute("SELECT question FROM questions")}
            net_new = sum(1 for (q, *_) in QUESTIONS if q not in existing)
            print(f"net new (estimated): {net_new}")
            print("\nDRY RUN — no writes. Re-run with --apply to seed.")
            conn.close()
            return

        # Snapshot before writing.
        from eklavya.backups import snapshot
        snap_id = snapshot("before seed_questions_expansion --apply")
        print(f"\nSnapshot taken: {snap_id}")

        conn.executemany(
            "INSERT OR IGNORE INTO questions(question, topic, difficulty, role, company, source) "
            "VALUES(?, ?, ?, ?, ?, ?)",
            [(q, t, d or None, r or None, c or None, s or None)
             for (q, t, d, r, c, s) in QUESTIONS],
        )
        conn.commit()
        after = conn.execute("SELECT COUNT(*) AS n FROM questions").fetchone()["n"]
        print(f"questions after:  {after}  (+{after - before} new rows inserted)")
    finally:
        conn.close()


if __name__ == "__main__":
    main(apply="--apply" in sys.argv)
